# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dna.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dna.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tdna.proto\"Z\n\x08\x44naProto\x12\x15\n\rlearning_rate\x18\x01 \x01(\x02\x12\x19\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\n.EdgeProto\x12\x1c\n\x06\x63onvex\x18\x03 \x03(\x0b\x32\x0c.ConvexProto\"\x99\x02\n\tEdgeProto\x12\x13\n\x0b\x66rom_vertex\x18\x01 \x01(\x05\x12\x11\n\tto_vertex\x18\x02 \x01(\x05\x12\x18\n\x10\x64\x65pth_precedence\x18\x03 \x01(\x05\x12\x18\n\x10scale_precedence\x18\x04 \x01(\x05\x12!\n\x04type\x18\x05 \x01(\x0e\x32\x13.EdgeProto.EdgeType\x1ai\n\x04\x43onv\x12\x14\n\x0c\x64\x65pth_factor\x18\x01 \x01(\x05\x12\x19\n\x11\x66ilter_half_width\x18\x02 \x01(\x05\x12\x1a\n\x12\x66ilter_half_height\x18\x03 \x01(\x05\x12\x14\n\x0cstride_scale\x18\x04 \x01(\x05\"\"\n\x08\x45\x64geType\x12\x08\n\x04\x43ONV\x10\x00\x12\x0c\n\x08IDENTITY\x10\x01\"\xcd\x01\n\x0b\x43onvexProto\x12\x16\n\x0einputs_mutable\x18\x01 \x01(\x05\x12\x17\n\x0foutputs_mutable\x18\x02 \x01(\x05\x12\x1a\n\x12properties_mutable\x18\x03 \x01(\x05\x12\x10\n\x08\x65\x64ges_in\x18\x04 \x03(\x05\x12\x11\n\tedges_out\x18\x05 \x03(\x05\x12%\n\x04type\x18\x06 \x01(\x0e\x32\x17.ConvexProto.ConvexType\"%\n\nConvexType\x12\n\n\x06LINEAR\x10\x00\x12\x0b\n\x07\x42N_RELU\x10\x01\x62\x06proto3')
)



_EDGEPROTO_EDGETYPE = _descriptor.EnumDescriptor(
  name='EdgeType',
  full_name='EdgeProto.EdgeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONV', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDENTITY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=353,
  serialized_end=387,
)
_sym_db.RegisterEnumDescriptor(_EDGEPROTO_EDGETYPE)

_CONVEXPROTO_CONVEXTYPE = _descriptor.EnumDescriptor(
  name='ConvexType',
  full_name='ConvexProto.ConvexType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LINEAR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BN_RELU', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=558,
  serialized_end=595,
)
_sym_db.RegisterEnumDescriptor(_CONVEXPROTO_CONVEXTYPE)


_DNAPROTO = _descriptor.Descriptor(
  name='DnaProto',
  full_name='DnaProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='DnaProto.learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges', full_name='DnaProto.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='convex', full_name='DnaProto.convex', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=103,
)


_EDGEPROTO_CONV = _descriptor.Descriptor(
  name='Conv',
  full_name='EdgeProto.Conv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth_factor', full_name='EdgeProto.Conv.depth_factor', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter_half_width', full_name='EdgeProto.Conv.filter_half_width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter_half_height', full_name='EdgeProto.Conv.filter_half_height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride_scale', full_name='EdgeProto.Conv.stride_scale', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=351,
)

_EDGEPROTO = _descriptor.Descriptor(
  name='EdgeProto',
  full_name='EdgeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_vertex', full_name='EdgeProto.from_vertex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_vertex', full_name='EdgeProto.to_vertex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_precedence', full_name='EdgeProto.depth_precedence', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale_precedence', full_name='EdgeProto.scale_precedence', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='EdgeProto.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EDGEPROTO_CONV, ],
  enum_types=[
    _EDGEPROTO_EDGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=387,
)


_CONVEXPROTO = _descriptor.Descriptor(
  name='ConvexProto',
  full_name='ConvexProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs_mutable', full_name='ConvexProto.inputs_mutable', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs_mutable', full_name='ConvexProto.outputs_mutable', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties_mutable', full_name='ConvexProto.properties_mutable', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges_in', full_name='ConvexProto.edges_in', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges_out', full_name='ConvexProto.edges_out', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ConvexProto.type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONVEXPROTO_CONVEXTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=595,
)

_DNAPROTO.fields_by_name['edges'].message_type = _EDGEPROTO
_DNAPROTO.fields_by_name['convex'].message_type = _CONVEXPROTO
_EDGEPROTO_CONV.containing_type = _EDGEPROTO
_EDGEPROTO.fields_by_name['type'].enum_type = _EDGEPROTO_EDGETYPE
_EDGEPROTO_EDGETYPE.containing_type = _EDGEPROTO
_CONVEXPROTO.fields_by_name['type'].enum_type = _CONVEXPROTO_CONVEXTYPE
_CONVEXPROTO_CONVEXTYPE.containing_type = _CONVEXPROTO
DESCRIPTOR.message_types_by_name['DnaProto'] = _DNAPROTO
DESCRIPTOR.message_types_by_name['EdgeProto'] = _EDGEPROTO
DESCRIPTOR.message_types_by_name['ConvexProto'] = _CONVEXPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DnaProto = _reflection.GeneratedProtocolMessageType('DnaProto', (_message.Message,), dict(
  DESCRIPTOR = _DNAPROTO,
  __module__ = 'dna_pb2'
  # @@protoc_insertion_point(class_scope:DnaProto)
  ))
_sym_db.RegisterMessage(DnaProto)

EdgeProto = _reflection.GeneratedProtocolMessageType('EdgeProto', (_message.Message,), dict(

  Conv = _reflection.GeneratedProtocolMessageType('Conv', (_message.Message,), dict(
    DESCRIPTOR = _EDGEPROTO_CONV,
    __module__ = 'dna_pb2'
    # @@protoc_insertion_point(class_scope:EdgeProto.Conv)
    ))
  ,
  DESCRIPTOR = _EDGEPROTO,
  __module__ = 'dna_pb2'
  # @@protoc_insertion_point(class_scope:EdgeProto)
  ))
_sym_db.RegisterMessage(EdgeProto)
_sym_db.RegisterMessage(EdgeProto.Conv)

ConvexProto = _reflection.GeneratedProtocolMessageType('ConvexProto', (_message.Message,), dict(
  DESCRIPTOR = _CONVEXPROTO,
  __module__ = 'dna_pb2'
  # @@protoc_insertion_point(class_scope:ConvexProto)
  ))
_sym_db.RegisterMessage(ConvexProto)


# @@protoc_insertion_point(module_scope)
